# Generated by Django 6.0.5 on 2026-06-17 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_connectgroup_membership_connectgroup_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='group',
            new_name='connect_group',
        ),
        migrations.AlterField(
            model_name='connectgroup',
            name='members',
            field=models.ManyToManyField(related_name='joined_groups', through='pages.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
